myapp/urls.py
from django.urls import path
from myapp import views
app_name = 'myapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.user_login, name='login'),
    path(r'myorders/', views.my_orders, name='orders'),
    path(r'about/', views.about, name='about'),
    path(r'<int:cat_no>', views.detail, name='cat_no'),
    path(r'products/', views.products, name='products'),
    path(r'place_order', views.place_order, name='place_order'),
    path(r'products/<int:prod_id>', views.productdetail, name='productdetail')
]

mysiteF22/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'myapp/', include('myapp.urls')),
]

myapp/models.py
import numbers

from django.db import models
import datetime
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=200)
    warehouse = models.CharField(max_length=100, default="Windsor", blank=False)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=100)
    length = models.IntegerField()
    pub_date = models.DateField()

    def __str__(self):
        return self.title


class Author(models.Model):
    name = models.CharField(max_length=50)
    books = models.ManyToManyField(Book)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField(default=100)
    available = models.BooleanField(default=True)
    description = models.TextField(max_length=100, blank=True)
    interested = models.PositiveIntegerField(default=0, blank=False)

    def __str__(self):
        return self.name

    def refill(self):
        self.stock = self.stock+100


class Client(User):
    PROVINCE_CHOICES = [('AB', 'Alberta'), ('MB', 'Manitoba'), ('ON', 'Ontario'), ('QC', 'Quebec'), ]
    company = models.CharField(max_length=50 , blank=True)
    shipping_address = models.CharField(max_length=300, null=True, blank=True)
    city = models.CharField(max_length=20 , default="Windsor")
    province = models.CharField(max_length=2, choices=PROVINCE_CHOICES, default='ON')
    interested_in = models.ManyToManyField(Category, related_name="clients")


class Order(models.Model):
    order_choices = [(0, 'Order Cancelled'), (1, 'Order Placed'), (2, 'Order Shipped'), (3, 'Order Delivered')]
    product = models.ForeignKey(Product, related_name="products", on_delete=models.CASCADE)
    client = models.ForeignKey(Client, related_name="clients", on_delete=models.CASCADE)
    num_units = models.PositiveIntegerField(default=100)
    order_status = models.IntegerField(default=1, choices=order_choices)
    status_date = models.DateField(max_length=30, blank=True, null=True)

    # def __str__(self):
    #     return self.product.name, self.product.price

    @staticmethod
    def total_cost():
        total = 0
        queryset = Order.objects.all()
        for x in queryset:
            total += x.product.price
        return total

myapp/forms.py
from django import forms
from myapp.models import Order, Client, Product


class OrderForm(forms.ModelForm):
    # order_choices = [(0, 'Order Cancelled'), (1, 'Order Placed'), (2, 'Order Shipped'), (3, 'Order Delivered')]
    # order_status = models.IntegerField(default=1, choices=order_choices)
    client = forms.ModelChoiceField(queryset=Client.objects.all(), label="Client Name", widget=forms.RadioSelect)
    product = forms.ModelChoiceField(queryset=Product.objects.all(), widget=forms.Select)
    num_units = forms.IntegerField(label="Quantity")
    # order_status = forms.ChoiceField(widget=forms.RadioSelect, choices=order_choices)
    # status_date = forms.DateField()

    class Meta:
        model = Order
        fields = ['client', 'product', 'num_units']


class InterestForm(forms.Form):
    CHOICES = [(1, "Yes"), (0, "No")]
    interested = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES)
    quantity = forms.IntegerField(min_value=1, initial=1)
    comments = forms.CharField(widget=forms.Textarea, required=False, label="Additional Comments")

myapp/views.py
import datetime

from django.contrib import messages
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.template import RequestContext
from django.urls import reverse
from django.utils import timezone

from .forms import OrderForm, InterestForm
from .models import Category, Product, Client, Order
from django.shortcuts import get_object_or_404
# Create your views here.


def index(request):
    cat_list = Category.objects.all().order_by('id')[:10]
    # response = HttpResponse()
    # heading1 = '<p>' + 'List of categories: ' + '</p>'
    # response.write(heading1)
    # for category in cat_list:
    #     para = '<p>' + str(category.id) + ': ' + str(category) + '</p>'
    #     response.write(para)
    # heading2 = '<p>' + 'List of Products: ' + '</p>'
    # response.write(heading2)
    # product_list = Product.objects.all().order_by('-price')[:5]
    # for product in product_list:
    #     para = '<p>' + str(product.id) + ': ' + str(product.name) + '</p>'
    #     response.write(para)
    # return response
    context = {
        'cat_list': cat_list,
        'user': request.user
    }
    return render(request, 'myapp/index.html', context=context)


def about(request):
    # para = '<h1>' + "This is an Online Store APP" + '</h1>'
    if 'about_visits' in request.COOKIES.keys():
        number_visits = request.COOKIES['about_visits']
        number_visits = int(number_visits) + 1
    else:
        number_visits = 1

    response = render(request, 'myapp/about.html', {'number_visits': number_visits})
    response.set_cookie('about_visits', value=number_visits, max_age=300)
    return response
    # return render(request, 'myapp/about.html')
    # if request.session.get('about_visits', False):
    #     request.session['about_visits'] = request.session.get('about_visits') +1
    # else:
    #     request.session['about_visits']=1
    #
    # return render(request, 'myapp/about.html', {'about_visits':  request.session.get('about_visits')})


def detail(request, cat_no):
    cat_obj = get_object_or_404(Category, pk=cat_no)
    # response = HttpResponse()
    # response.write('<h1>' + cat_obj.warehouse + '</h1>')
    prod_obj = Product.objects.filter(category=cat_obj)
    #     para = '<p>' + str(product.id) + ': ' + str(product.name) + '</p>'
    #     response.write(para)
    return render(request, 'myapp/detail.html', {'cat_obj': cat_obj, 'prod_obj': prod_obj})


def products(request):
    prodlist = Product.objects.all().order_by('id')
    return render(request, 'myapp/products.html', {'prodlist': prodlist})


def place_order(request):
    msg = ''
    prodlist = Product.objects.all()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if order.num_units <= order.product.stock:
                order.save()
                msg = 'Your order has been placed successfully.'
                order.product.refill()
                order.save()
            else:
                msg = 'We do not have sufficient stock to fill yourorder.'
            return render(request, 'myapp/order_response.html', {'msg': msg})
    else:
        form = OrderForm()
    return render(request, 'myapp/place_order.html', {'form': form, 'msg': msg, 'prodlist': prodlist})


def productdetail(request, prod_id):
    prod_obj = get_object_or_404(Product, pk=prod_id)
    if request.method == 'POST':
        form = InterestForm(request.POST)
        # breakpoint()
        if form.is_valid():
            # detailform = form.save(commit=False)
            if int(form.data['interested']) == 1:
                prod_obj.interested = prod_obj.interested+1

                prod_obj.save()
                # form.save()
            return render(request, 'myapp/productdetail.html', {'form': form, 'prod_obj': prod_obj})
    else:
        form = InterestForm()
    return render(request, 'myapp/productdetail.html', {'form': form, 'prod_obj': prod_obj})


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                HttpResponse(user.last_login)
                # if request.session.get_expiry_age()==0:
                #     msg = "Your last login was more than 1 hour ago"
                if 'last_login' in request.session:
                    session_obj = str(request.session['last_login'])
                    msg = "Last login date and time:" + str(request.session['last_login'])
                    messages.success(request, 'Last login date and time: ' + str(request.session['last_login']))
                    render(request, 'myapp/index.html', {'last_login': session_obj})
                else:
                    request.session['last_login'] = str(timezone.now())
                    # print(request.session['last_login'])
                    msg = "Your last login was more than 1 hour ago"
                    render(request, 'myapp/index.html', {'last_login': msg})

                # request.session['last_login'] = str(timezone.now())

                request.session['username'] = username
                request.session['user_first_name'] = user.first_name
                request.session['user_last_name'] = user.last_name
                request.session.set_expiry(30)

                return HttpResponseRedirect(reverse('myapp:index'))

            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        return render(request, 'myapp/login.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('myapp:index'))


@login_required
def my_orders(request):
    # username = login.__name__
    user = request.user
    client_obj = Client.objects.filter(id=user.id)
    if client_obj:
        orderobj = Order.objects.filter(client__id=client_obj[0].id)
        return render(request, 'myapp/myorders.html', {'orderobj': orderobj})
    else:
        return HttpResponse('You are not a registered client!')

myapp/templates/myapp/about.html
<!DOCTYPE html>
{% extends 'myapp/base.html' %}
{% block myhdg %}
    <div>
        <h1> Hello PyDevs</h1>
    </div>
{% endblock %}
{% block title %}
    About Page
{% endblock %}
{% block body_block %}
    <p> <h1>This is an About Page</h1></p>
    <p> Number of times this page has been visited: {{ about_visits }}</p>
{#    <p><a href="/myapp">Index page</a></p>#}
{#    <p><a href="{% url 'myapp:index' %}"> Index page </a></p>#}
{% endblock %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About Page</title>
</head>
<body>

</body>
</html>

myapp/templates/myapp/about0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About Page</title>
</head>
<body>
    <p> <h1>This is an About Page</h1></p>
    <p><a href="/myapp">Index page</a></p>
    <p><a href="{% url 'myapp:index' %}"> Index page </a></p>
</body>
</html>

myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'myapp/style1.css' %}"/>
        <title>Online Store APP - {% block title %}Welcome!{% endblock %}</title>
    </head>
    <body>
        <div>
            <h1>{% block myhdg %}Hello User {% endblock %}</h1>
            {% block body_block %}*** {% endblock %}
        </div>
        <hr />
         <div>
        <ul>
        {% block line_block %}
            <li class="hbar1">
                <a href="/myapp/about">Find out about this site</a>
            </li>
            <li class="hbar1">
                <a href="{% url 'myapp:index' %}">Click here to return to main page</a>
            </li>
            <li class="hbar1"><a href="{% url 'myapp:products' %}">Click here to
            see products</a></li>
            {% if user.is_authenticated %}
{#                <li class="hbar1"><a href="{% url 'myapp:logout' %}">Logout</a></li>#}
            {% else %}
                <li class="hbar1"><a href="{% url 'myapp:login' %}">Login</a></li>
            {% endif %}
            <li class="hbar1"><a href="{% url 'myapp:index' %}">Click here to
                return to main page</a><br/></li>
        {% endblock %}

        </ul>
    </div>
        <div>
            <ul>
{#                <li class="hbar1"><a href="/myapp/about">Find out about this site</a></li>#}
{#                <li class="hbar1"><a href = "{% url 'myapp:index' %}">Click here to return to main page</a><br/></li>#}
{#                <li class="hbar1"><a href="/myapp/products">List of available products</a></li>#}
            </ul>
        </div>
    </body>
</html>

myapp/templates/myapp/detail.html
<!DOCTYPE html>
{% extends 'myapp/base.html' %}
{% block myhdg %}
    <div>
        <h1> Hello PyDevs</h1>
    </div>
{% endblock %}
{% block title %}
    Category description
{% endblock %}
{% block body_block %}
    <h2>Category selected:  {{ cat_obj.name }}</h2>
    <p>Name: {{ cat_obj.name}}</p>
    <p>Warehouse: {{ cat_obj.name}}</p>
    {% if prod_obj %}
    <h2>List of Products</h2>
    <ol>
        {% for prod in prod_obj %}
            <li> {{ prod.name}} </li>
        {% endfor %}
    </ol>

    {% else %}
        <strong>There are no available products!</strong>
    {% endif %}
    <p><a href="{% url 'myapp:index' %}"> Index page </a></p>
{% endblock %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details of Category</title>
</head>
<body>

</body>
</html>

myapp/templates/myapp/detail0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details of the category</title>
</head>
<body>
    <h2>Category selected:  {{ cat_obj.name }}</h2>
    <p>Name: {{ cat_obj.name}}</p>
    <p>Warehouse: {{ cat_obj.name}}</p>
    {% if prod_obj %}
    <h2>List of Products</h2>
    <ol>
        {% for prod in prod_obj %}
            <li> {{ prod.name}} </li>
        {% endfor %}
    </ol>

    {% else %}
        <strong>There are no available products!</strong>
    {% endif %}
    <p><a href="{% url 'myapp:index' %}"> Index page </a></p>
</body>
</html>

myapp/templates/myapp/index.html
<!DOCTYPE html>
{% extends 'myapp/base.html' %}
{% block myhdg %}
    <div>
        <h1> Hello PyDevs</h1>
     {% if user.is_authenticated %}
            Hello {{ user.username }}
    {% endif %}
    <p>{{ last_login }}</p>
    </div>
{% endblock %}
{% block title %}
    Category list
{% endblock %}
{% block link_block %}
    <li class="hbar1"><a href="/myapp/about/">Find out about this
        site</a></li>
    <li class="hbar1"><a href="{% url 'myapp:products' %}">Click here to
        see products</a></li>
    {% if user.is_authenticated %}
{#        <li class="hbar1"><a href="{% url 'myapp:logout' %}">Logout</a></li>#}
    {% else %}
        <li class="hbar1"><a href="{% url 'myapp:login' %}">Login</a></li>
    {% endif %}<br/></li>
{% endblock link_block %}
{% block body_block %}

    {% if cat_list %}
    <h2>List of Categories</h2>
    <ol>
        {% for cat in cat_list %}
            <li> {{ cat.name}} </li>
        {% endfor %}
    </ol>

    {% else %}
        <strong>There are no available categories!</strong>
    {% endif %}
{#    <p><a href="/myapp/about">About page</a></p>#}
{#    <p><a href="{% url "myapp:about" %}"> About page </a></p>#}
{% endblock %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Online Store App</title>
</head>
<body>

</body>
</html>

myapp/templates/myapp/index0.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Online Store APP</title>
</head>
<body>
    {% if cat_list %}
    <h2>List of Categories</h2>
    <ol>
        {% for cat in cat_list %}
            <li> {{ cat.name}} </li>
        {% endfor %}
    </ol>

    {% else %}
        <strong>There are no available categories!</strong>
    {% endif %}
    <p><a href="/myapp/about">About page</a></p>
    <p><a href="{% url "myapp:about" %}"> About page </a></p>
</body>
</html>

myapp/templates/myapp/login.html
<!DOCTYPE html>
{% extends 'myapp/base.html' %}
{% block myhdg %}
    <div>
        <h1> Hello PyDevs</h1>
    </div>
{% endblock %}
{% block title %}
    Login Page
{% endblock %}
{% block body_block %}
    <h1> Welcome! Login to continue to homepage
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <p>
            <label for="username">Username:</label>
            <input type="text" value="" placeholder="Username" id="username" name="username">
        </p>
        <p>
            <label for="password">Password:</label>
            <input type="password" value="" placeholder="Password" id="password" name="password">
        </p>
        <p><input type="submit" value="Submit"></p>
    </form>
{#    <p><a href="{% url 'myapp:index' %}"> Index page </a></p>#}
{% endblock %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login Page</title>
</head>
<body>

</body>
</html>

myapp/templates/myapp/myorders.html
<!DOCTYPE html>
{% extends 'myapp/base.html' %}
{% block myhdg %}
    <div>
        <h1> Hello PyDevs</h1>
    </div>
{% endblock %}
{% block title %}
    Order Detail
{% endblock %}
{% block body_block %}
    {% if orderobj %}
    <ol>
        {% for x in orderobj %}
            <li> {{ x.client }} </li>
            <li> {{ x.product.name }} </li>
            <li> {{ x.order_choices }} </li>
            <li> {{ x.order_status }} </li>
            <li> {{ x.status_date }} </li>
        {% endfor %}
    </ol>
    {% else %}
        <strong>There are no orders!</strong>
    {% endif %}

{% endblock %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details of Product</title>
</head>
<body>

</body>
</html>

myapp/templates/myapp/order_response.html
<!DOCTYPE html>
{% extends 'myapp/base.html' %}
{% block myhdg %}
    <div>
        <h1> Hello PyDevs</h1>
    </div>
{% endblock %}
{% block title %}
    Order Response
{% endblock %}
{% block body_block %}

    <h2>Order details</h2>
    <p> {{ msg.capitalize }}</p>
{#    <p><a href="{% url 'myapp:index' %}"> Index page </a></p>#}
{% endblock %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order Details</title>
</head>
<body>

</body>
</html>

myapp/templates/myapp/place_order.html
<!DOCTYPE html>
{% extends 'myapp/base.html' %}
{% block myhdg %}
    <div>
        <h1> Hello PyDevs</h1>
    </div>
{% endblock %}
{% block title %}
    Place Order
{% endblock %}
{% block body_block %}
    {% if prodlist %}
    <h2>List of Products</h2>
    <ol>
        {% for prod in prodlist %}
            <li> Name: {{ prod.name }} <br> Price: {{ prod.price }}</li>
        {% endfor %}
    </ol>

    {% else %}
        <strong>There are no available products!</strong>
    {% endif %}
    <form action="place_order" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>
{#    <p><a href="{% url 'myapp:index' %}"> Index page </a></p>#}
{% endblock %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Place an order</title>
</head>
<body>

</body>
</html>

myapp/templates/myapp/productdetail.html
<!DOCTYPE html>
{% extends 'myapp/base.html' %}
{% block myhdg %}
    <div>
        <h1> Hello PyDevs</h1>
    </div>
{% endblock %}
{% block title %}
    Product Detail
{% endblock %}
{% block body_block %}
    {% if prod_obj %}
    <h2>Product selected:  {{ prod_obj.name }}</h2>
    <p>Name: {{ prod_obj.name}}</p>
    <p>Price: {{ prod_obj.price }}</p>
    <p>Interested: {{ prod_obj.interested }}</p>
    <p>Stock: {{ prod_obj.stock }}</p>
    <p>Category: {{ prod_obj.category }}</p>
    {% else %}
        <strong>Error in product number!</strong>
    {% endif %}
    <form  action="" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>
{% endblock %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details of Product</title>
</head>
<body>

</body>
</html>

myapp/templates/myapp/products.html
<!DOCTYPE html>
{% extends 'myapp/base.html' %}
{% block myhdg %}
    <div>
        <h1> Hello PyDevs</h1>
    </div>
{% endblock %}
{% block title %}
    Product list
{% endblock %}
{% block body_block %}
    {% if prodlist %}
    <h2>List of Products</h2>
    <ol>
        {% for prod in prodlist %}
            <li> {{ prod.name}} </li>
        {% endfor %}
    </ol>

    {% else %}
        <strong>There are no available products!</strong>
    {% endif %}
    <p><a href="{% url 'myapp:place_order' %}"> Click to place an order </a></p>
{% endblock %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List of available products</title>
</head>
<body>

</body>
</html>